### PR TITLE
fix: template short flag

### PR DESCRIPTION
**Pull request by mgorsk1**
Since there is already shorthand flag `-t` for title, remove it from click option related to `--template`

### CODE REVIEW

**Comment by mgorsk1** [comment]
cc @KeNaCo

**Comment by mgorsk1** [comment]
thanks @KeNaCo do you think it's enough for a new pypi release ?

**Comment by KeNaCo** [comment]
Agree. But this week is pretty dense for me. So I will try Friday or the weekend.

**Comment by KeNaCo** [comment]
So, later better than never. New version released.

**Pull request merged**
